In [19]:
import numpy as np
# 1
print("a", np.arange(1, 10 + 1))
print("b", np.arange(0.5, 5 + 1, 0.25))

a [ 1  2  3  4  5  6  7  8  9 10]
b [0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.   5.25 5.5  5.75]


In [21]:
# 2
print("a", np.zeros(10, dtype = int))
print("b", np.zeros((3, 4), dtype = int))

a [0 0 0 0 0 0 0 0 0 0]
b [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [23]:
# 3
print("a", np.linspace(2, 12, 5, dtype = int))
print("b", np.linspace(3, 9, 4, dtype = int))

a [ 2  4  7  9 12]
b [3 5 7 9]


In [43]:
# 4
l1 = np.random.rand(4, 2)
print("a", np.round(l1, 2))
print("b", np.random.randint(10, 20 + 1, (3, 3)))
print("c", np.reshape(l1, (8, 1)))

# When using "reshape" it is important to note that the new matrix must be of the appropriate size.

a [[0.65 0.7 ]
 [0.89 0.6 ]
 [0.5  0.71]
 [0.27 0.49]]
b [[17 14 14]
 [10 18 17]
 [12 19 18]]
c [[0.6534314 ]
 [0.70113727]
 [0.89106851]
 [0.59943212]
 [0.50128619]
 [0.70598837]
 [0.27453949]
 [0.48907476]]


# 5
# Constant seed value will always produce the same sequence of random numbers.

## The advantage of using seed() is that it allows you to capture a sequence of random numbers. This can help in:

- machine learning (to compare models on the same data),
  
- testing (to check that the code works correctly),

- scientific computing (to reproduce the results of an experiment).